spring.application.name=ms-reportes
server.port=${PORT:8081}

# CONEXIÓN A POSTGRESQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/db_reportes_valle}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Arucutipa123}


# CONFIGURACIÓN DE HIBERNATE / JPA
spring.jpa.hibernate.ddl-auto=update

# Muestra el SQL en la consola (útil para ver qué hace Spring por detrás)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Especifica el dialecto de PostgreSQL
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect